### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by vackyton** [snipergaming888/fnf-sniper-engine#1]
So is sniper engine buggy and can you make the online version open source?
Edit: Can you change the assets with a mod assets then will sniper engine still be there?

**Comment by snipergaming888** [comment]
> So is sniper engine buggy and can you make the online version open source?
there are a few bugs I know of but nightly 5 should fix them, in order to use the online version compile for html5.
> Edit: Can you change the assets with a mod assets then will sniper engine still be there?
yes, just make sure the mode uses Kade Engine asset system, except sniper engine nightly 5 moves the week 6 assets location.

**Comment by vackyton** [comment]
ok And can you upload the online version or is not available and are you ever going to make a site like funkin.online or are you going to upload mods on snipergaming cause it is blocked for me but i was able to fork it and thats why i wanted you to update the old site or atleast make the source public on github for funkin.online.

**Comment by vackyton** [comment]
hey sniper why are there hex assets in the files?

**Comment by snipergaming888** [comment]
There's something secret hidden in the main menu

**Comment by vackyton** [comment]
yea i just saw hex data .json file lol
